language: php

php:
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return

  # install dependencies in parallel
  - travis_retry composer global require hirak/prestissimo

install:
  - composer install

script:
  - echo "${BEAST_KEY}" > tests/testToken

  # Run PHPUnit
  - bin/phpunit --bootstrap vendor/autoload.php --configuration phpunit.xml --fail-on-warning

  # Check if the code standards weren't broken.
  # Run it only on PHP 7.2 which should be the fastest. No need to run it for all PHP versions
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then bin/php-cs-fixer fix -v --dry-run --diff; fi